title: Brett Tolbert
description: Software Developer
email: bretttolbert@gmail.com
baseurl: ""
url: "https://bretttolbert.github.io"
repository: bretttolbert/bretttolbert.github.io # used by the jekyll-github-metadata plugin

theme: jekyll-theme-cayman # Use a GitHub Pages supported theme see https://github.com/pages-themes/

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

include:
  - README.md
  - LICENSE
